/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    projects: Project;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    navigation: Navigation;
    home: Home;
    'section-text': SectionText;
    'case-study': CaseStudy;
    about: About;
    career: Career;
    'ui-strings': UiString;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'section-text': SectionTextSelect<false> | SectionTextSelect<true>;
    'case-study': CaseStudySelect<false> | CaseStudySelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    career: CareerSelect<false> | CareerSelect<true>;
    'ui-strings': UiStringsSelect<false> | UiStringsSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Las páginas del sitio, construidas con bloques. Arrastra bloques para armar cada página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * la dirección de la página, p.ej. proyectos/branding; usa '' o 'home' para la portada
   */
  slug: string;
  /**
   * Cómo aparece esta página en el menú de navegación.
   */
  menuLabel?: string | null;
  showInNav?: boolean | null;
  /**
   * El número menor aparece primero.
   */
  navOrder?: number | null;
  /**
   * Añade y ordena los bloques que forman esta página.
   */
  layout?:
    | (
        | HeroBlock
        | PortfolioSectionBlock
        | ProjectGalleryBlock
        | SectionHeadingBlock
        | RichTextBlock
        | TwoColumnBlock
        | DetailsTableBlock
        | TimelineBlock
        | JourneyMapBlock
        | PersonaCardsBlock
        | QABlock
        | InfoColumnsBlock
        | ExperienceAccordionBlock
        | ContactBlock
        | ImageBlock
        | CTAButtonBlock
        | SpacerBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Imagen de fondo de la portada (elígela de la biblioteca).
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Solo si no usas una imagen de la biblioteca: ruta del archivo, p. ej. /images/hero-background.jpg
   */
  backgroundImagePath?: string | null;
  /**
   * El título grande de la portada.
   */
  title?: string | null;
  subtitle?: string | null;
  /**
   * Párrafo de introducción bajo el título.
   */
  body?: string | null;
  /**
   * Texto del primer botón.
   */
  cta1?: string | null;
  /**
   * Texto del segundo botón.
   */
  cta2?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Todas las imágenes subidas. Sube aquí una imagen antes de usarla en un proyecto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Breve descripción de la imagen (para accesibilidad). Sirve también como nombre en la biblioteca.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioSectionBlock".
 */
export interface PortfolioSectionBlock {
  heading?: string | null;
  description?: string | null;
  /**
   * Igual en ambos idiomas.
   */
  studioName?: string | null;
  roleDescription?: string | null;
  ctaLabel?: string | null;
  /**
   * A dónde lleva el botón. Igual en ambos idiomas.
   */
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolioSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectGalleryBlock".
 */
export interface ProjectGalleryBlock {
  /**
   * ¿Cómo eliges las imágenes que se muestran?
   */
  source: 'by-filter' | 'manual' | 'items';
  /**
   * ¿De qué sección tomar las imágenes?
   */
  section?: ('branding' | 'web-apps' | 'uxui-producto' | 'fotografia-producto' | 'marketing-360') | null;
  /**
   * Filtra por el campo "Dónde se muestra" de cada proyecto.
   */
  placement?: ('home' | 'page' | 'both') | null;
  /**
   * Opcional. Solo para Branding: subgrupo (p. ej. deportes, belleza, logos).
   */
  group?: string | null;
  /**
   * Elige a mano las tarjetas de proyecto que quieres mostrar (todas del mismo tamaño).
   */
  projects?: (number | Project)[] | null;
  /**
   * Elige cada tarjeta y su tamaño en el mosaico (para reproducir el diseño exacto).
   */
  items?:
    | {
        project: number | Project;
        /**
         * El tamaño/espacio que ocupa esta tarjeta en la cuadrícula.
         */
        size: 'normal' | 'col3' | 'col4' | 'hero' | 'wide-tall' | 'wide5-tall' | 'tall' | 'med';
        id?: string | null;
      }[]
    | null;
  /**
   * Cómo se distribuyen las tarjetas.
   */
  layoutVariant: 'grid-3' | 'grid-4' | 'single' | 'masonry-photo' | 'masonry-6' | 'masonry-8' | 'masonry-10';
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectGallery';
}
/**
 * Las tarjetas con imagen de cada proyecto. Elige la página y dónde se muestra.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * ¿En qué página aparece esta imagen?
   */
  section: 'branding' | 'web-apps' | 'uxui-producto' | 'fotografia-producto' | 'marketing-360';
  /**
   * Elige dónde aparece esta tarjeta.
   */
  placement: 'home' | 'page' | 'both';
  /**
   * Solo para Branding: subgrupo (p. ej. deportes, belleza, logos).
   */
  group?: string | null;
  image: number | Media;
  /**
   * Número para ordenar dentro de su grupo (el menor aparece primero).
   */
  order: number;
  title?: string | null;
  alt?: string | null;
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock".
 */
export interface SectionHeadingBlock {
  eyebrow?: string | null;
  number?: string | null;
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionHeading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  heading?: string | null;
  paragraphs?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock".
 */
export interface TwoColumnBlock {
  left?: {
    label?: string | null;
    text?: string | null;
  };
  right?: {
    label?: string | null;
    text?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumn';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsTableBlock".
 */
export interface DetailsTableBlock {
  title?: string | null;
  rows?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'detailsTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  title?: string | null;
  durationLabel?: string | null;
  durationValue?: string | null;
  phases?:
    | {
        phase?: string | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JourneyMapBlock".
 */
export interface JourneyMapBlock {
  title?: string | null;
  intro?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  labels?: {
    action?: string | null;
    thought?: string | null;
    friction?: string | null;
  };
  stages?:
    | {
        number?: string | null;
        name?: string | null;
        action?: string | null;
        thought?: string | null;
        friction?: string | null;
        id?: string | null;
      }[]
    | null;
  qa?:
    | {
        question?: string | null;
        answer?: string | null;
        bullets?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'journeyMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonaCardsBlock".
 */
export interface PersonaCardsBlock {
  title?: string | null;
  intro?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  qa?:
    | {
        question?: string | null;
        answer?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  sectionLabels?: {
    basicInfo?: string | null;
    channels?: string | null;
    motivations?: string | null;
    painPoints?: string | null;
  };
  cards?:
    | {
        name?: string | null;
        descriptor?: string | null;
        quote?: string | null;
        basicInfo?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        channels?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        motivations?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        painPoints?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'personaCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QABlock".
 */
export interface QABlock {
  title?: string | null;
  items?:
    | {
        question?: string | null;
        answer?: string | null;
        bullets?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'qa';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoColumnsBlock".
 */
export interface InfoColumnsBlock {
  headings?: {
    education?: string | null;
    tools?: string | null;
    languages?: string | null;
  };
  education?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Igual en ambos idiomas.
   */
  tools?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Igual en ambos idiomas.
   */
  languages?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceAccordionBlock".
 */
export interface ExperienceAccordionBlock {
  headings?: {
    careerPath?: string | null;
    professionalExperience?: string | null;
  };
  experience?:
    | {
        role?: string | null;
        period?: string | null;
        responsibilities?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'experienceAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  heading?: string | null;
  body?: string | null;
  email?: string | null;
  phone?: string | null;
  socialLinks?:
    | {
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    copyrightPrefix?: string | null;
    rights?: string | null;
    privacy?: string | null;
    terms?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  caption?: string | null;
  width?: ('full' | 'contained' | 'half') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTAButtonBlock".
 */
export interface CTAButtonBlock {
  label?: string | null;
  href?: string | null;
  style?: ('primary' | 'secondary' | 'link') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaButton';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  size: 'small' | 'medium' | 'large' | 'xlarge';
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * Las personas que pueden entrar a este panel de administración.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  menuLabel?: T;
  showInNav?: T;
  navOrder?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        portfolioSection?: T | PortfolioSectionBlockSelect<T>;
        projectGallery?: T | ProjectGalleryBlockSelect<T>;
        sectionHeading?: T | SectionHeadingBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        twoColumn?: T | TwoColumnBlockSelect<T>;
        detailsTable?: T | DetailsTableBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        journeyMap?: T | JourneyMapBlockSelect<T>;
        personaCards?: T | PersonaCardsBlockSelect<T>;
        qa?: T | QABlockSelect<T>;
        infoColumns?: T | InfoColumnsBlockSelect<T>;
        experienceAccordion?: T | ExperienceAccordionBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        ctaButton?: T | CTAButtonBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  backgroundImagePath?: T;
  title?: T;
  subtitle?: T;
  body?: T;
  cta1?: T;
  cta2?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioSectionBlock_select".
 */
export interface PortfolioSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  studioName?: T;
  roleDescription?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectGalleryBlock_select".
 */
export interface ProjectGalleryBlockSelect<T extends boolean = true> {
  source?: T;
  section?: T;
  placement?: T;
  group?: T;
  projects?: T;
  items?:
    | T
    | {
        project?: T;
        size?: T;
        id?: T;
      };
  layoutVariant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock_select".
 */
export interface SectionHeadingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  number?: T;
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  heading?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock_select".
 */
export interface TwoColumnBlockSelect<T extends boolean = true> {
  left?:
    | T
    | {
        label?: T;
        text?: T;
      };
  right?:
    | T
    | {
        label?: T;
        text?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsTableBlock_select".
 */
export interface DetailsTableBlockSelect<T extends boolean = true> {
  title?: T;
  rows?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  title?: T;
  durationLabel?: T;
  durationValue?: T;
  phases?:
    | T
    | {
        phase?: T;
        duration?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JourneyMapBlock_select".
 */
export interface JourneyMapBlockSelect<T extends boolean = true> {
  title?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  labels?:
    | T
    | {
        action?: T;
        thought?: T;
        friction?: T;
      };
  stages?:
    | T
    | {
        number?: T;
        name?: T;
        action?: T;
        thought?: T;
        friction?: T;
        id?: T;
      };
  qa?:
    | T
    | {
        question?: T;
        answer?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonaCardsBlock_select".
 */
export interface PersonaCardsBlockSelect<T extends boolean = true> {
  title?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  qa?:
    | T
    | {
        question?: T;
        answer?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  sectionLabels?:
    | T
    | {
        basicInfo?: T;
        channels?: T;
        motivations?: T;
        painPoints?: T;
      };
  cards?:
    | T
    | {
        name?: T;
        descriptor?: T;
        quote?: T;
        basicInfo?:
          | T
          | {
              text?: T;
              id?: T;
            };
        channels?:
          | T
          | {
              text?: T;
              id?: T;
            };
        motivations?:
          | T
          | {
              text?: T;
              id?: T;
            };
        painPoints?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QABlock_select".
 */
export interface QABlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoColumnsBlock_select".
 */
export interface InfoColumnsBlockSelect<T extends boolean = true> {
  headings?:
    | T
    | {
        education?: T;
        tools?: T;
        languages?: T;
      };
  education?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tools?:
    | T
    | {
        value?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceAccordionBlock_select".
 */
export interface ExperienceAccordionBlockSelect<T extends boolean = true> {
  headings?:
    | T
    | {
        careerPath?: T;
        professionalExperience?: T;
      };
  experience?:
    | T
    | {
        role?: T;
        period?: T;
        responsibilities?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  email?: T;
  phone?: T;
  socialLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        copyrightPrefix?: T;
        rights?: T;
        privacy?: T;
        terms?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTAButtonBlock_select".
 */
export interface CTAButtonBlockSelect<T extends boolean = true> {
  label?: T;
  href?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  section?: T;
  placement?: T;
  group?: T;
  image?: T;
  order?: T;
  title?: T;
  alt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * El menú principal del sitio. Ordena los enlaces arrastrándolos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * El nombre que aparece a la izquierda del menú.
   */
  brand?: string | null;
  /**
   * Cada fila es un enlace del menú. El orden aquí es el orden en el menú.
   */
  items?:
    | {
        label?: string | null;
        linkType: 'page' | 'custom' | 'anchor';
        page?: (number | null) | Page;
        url?: string | null;
        /**
         * Salta a esta sección cuando ya estás en la portada.
         */
        anchor?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * El texto de la portada (la parte de arriba de la página de inicio).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    /**
     * Ruta del archivo de la imagen de fondo de la portada.
     */
    backgroundImage?: string | null;
    /**
     * El título grande de la portada.
     */
    title?: string | null;
    subtitle?: string | null;
    /**
     * Párrafo de introducción bajo el título.
     */
    body?: string | null;
    /**
     * Texto del primer botón.
     */
    cta1?: string | null;
    /**
     * Texto del segundo botón.
     */
    cta2?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Los títulos y textos que aparecen encima de cada grupo de proyectos (en la vista previa de la página de inicio y en las páginas de proyectos).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-text".
 */
export interface SectionText {
  id: number;
  /**
   * Controla los textos de la sección "Web y Apps".
   */
  webApps?: {
    /**
     * Se muestra en la vista previa de esta sección en la página de inicio.
     */
    home?: {
      heading?: string | null;
      description?: string | null;
      studioName?: string | null;
      roleDescription?: string | null;
      cta?: string | null;
    };
    /**
     * Se muestra arriba de la página de este proyecto.
     */
    page?: {
      title?: string | null;
      description?: string | null;
    };
  };
  /**
   * Controla los textos de la sección "Branding".
   */
  branding?: {
    /**
     * Se muestra en la vista previa de esta sección en la página de inicio.
     */
    home?: {
      heading?: string | null;
      description?: string | null;
      studioName?: string | null;
      roleDescription?: string | null;
      cta?: string | null;
      sectionHeading?: string | null;
    };
    /**
     * Se muestra arriba de la página de este proyecto.
     */
    page?: {
      title?: string | null;
      description?: string | null;
      subtitleSports?: string | null;
      subtitleBeauty?: string | null;
    };
  };
  /**
   * Controla los textos de la sección "Fotografía de Producto".
   */
  photography?: {
    /**
     * Se muestra en la vista previa de esta sección en la página de inicio.
     */
    home?: {
      heading?: string | null;
      description?: string | null;
      studioName?: string | null;
      roleDescription?: string | null;
      cta?: string | null;
    };
    /**
     * Se muestra arriba de la página de este proyecto.
     */
    page?: {
      title?: string | null;
      description?: string | null;
    };
  };
  /**
   * Controla los textos de la sección "Marketing 360°".
   */
  marketing360?: {
    /**
     * Se muestra en la vista previa de esta sección en la página de inicio.
     */
    home?: {
      heading?: string | null;
      description?: string | null;
      studioName?: string | null;
      roleDescription?: string | null;
      cta?: string | null;
    };
    /**
     * Se muestra arriba de la página de este proyecto.
     */
    page?: {
      title?: string | null;
      description?: string | null;
    };
  };
  /**
   * Controla los textos de la sección "UX/UI". (El contenido completo del caso de estudio está en "Caso de Estudio UX/UI".)
   */
  uxui?: {
    /**
     * Se muestra en la vista previa de esta sección en la página de inicio.
     */
    home?: {
      heading?: string | null;
      tagline?: string | null;
      description?: string | null;
      studioName?: string | null;
      roleDescription?: string | null;
      sketchImage?: string | null;
      sketchAlt?: string | null;
      cta?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Todo el contenido de la página del caso de estudio (Snaga).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-study".
 */
export interface CaseStudy {
  id: number;
  /**
   * Título y lema en la parte superior de la página.
   */
  header?: {
    title?: string | null;
    tagline?: string | null;
  };
  /**
   * La imagen grande de portada del caso de estudio.
   */
  hero?: {
    image?: string | null;
    alt?: string | null;
  };
  /**
   * Nombre, subtítulo y resumen del proyecto.
   */
  project?: {
    name?: string | null;
    subtitle?: string | null;
    /**
     * Puntos de resumen (etiqueta + texto).
     */
    overview?:
      | {
          label?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Párrafos de introducción del caso de estudio.
   */
  intro?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * El problema detectado y la solución propuesta.
   */
  problemSolution?: {
    problem?: {
      label?: string | null;
      text?: string | null;
    };
    solution?: {
      label?: string | null;
      text?: string | null;
    };
  };
  /**
   * Tabla de herramientas, equipo y rol.
   */
  details?: {
    headers?: {
      tools?: string | null;
      team?: string | null;
      role?: string | null;
    };
    rows?:
      | {
          tools?: string | null;
          team?: string | null;
          role?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Duración y fases del proyecto.
   */
  timeline?: {
    title?: string | null;
    durationLabel?: string | null;
    durationValue?: string | null;
    phases?:
      | {
          phase?: string | null;
          duration?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Etapas y preguntas del recorrido del usuario.
   */
  journey?: {
    title?: string | null;
    intro?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    labels?: {
      action?: string | null;
      thought?: string | null;
      friction?: string | null;
    };
    stages?:
      | {
          number?: string | null;
          name?: string | null;
          action?: string | null;
          thought?: string | null;
          friction?: string | null;
          id?: string | null;
        }[]
      | null;
    qa?:
      | {
          question?: string | null;
          answer?: string | null;
          bullets?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Perfiles de usuarios tipo del proyecto.
   */
  personas?: {
    title?: string | null;
    intro?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    qa?:
      | {
          question?: string | null;
          answer?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    sectionLabels?: {
      basicInfo?: string | null;
      channels?: string | null;
      motivations?: string | null;
      painPoints?: string | null;
    };
    cards?:
      | {
          name?: string | null;
          descriptor?: string | null;
          quote?: string | null;
          basicInfo?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          channels?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          motivations?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          painPoints?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Sección de bocetos e ideas iniciales.
   */
  sketches?: {
    title?: string | null;
    intro?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    qa?:
      | {
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Conclusiones y aprendizajes del proyecto.
   */
  learnings?: {
    title?: string | null;
    qa?:
      | {
          question?: string | null;
          answer?:
            | {
                text?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Formación, herramientas, idiomas, datos de contacto y pie de página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Los títulos que encabezan cada bloque en la página "Sobre mí".
   */
  headings?: {
    education?: string | null;
    tools?: string | null;
    languages?: string | null;
  };
  /**
   * Lista de tu formación académica (una línea por estudio).
   */
  education?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Programas y herramientas que usas (igual en ambos idiomas).
   */
  tools?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Idiomas que hablas y tu nivel (igual en ambos idiomas).
   */
  languages?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bloque de contacto de la página.
   */
  contact?: {
    heading?: string | null;
    body?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Enlaces a tus redes sociales (igual en ambos idiomas).
   */
  socialLinks?:
    | {
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Textos del pie de página (aparece en todas las páginas).
   */
  footer?: {
    copyrightPrefix?: string | null;
    rights?: string | null;
    privacy?: string | null;
    terms?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tu trayectoria profesional (el acordeón de experiencia).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career".
 */
export interface Career {
  id: number;
  /**
   * Títulos que encabezan la sección de experiencia.
   */
  headings?: {
    careerPath?: string | null;
    professionalExperience?: string | null;
  };
  /**
   * Cada puesto de trabajo. Se muestran en orden, del primero al último.
   */
  experience?:
    | {
        role?: string | null;
        period?: string | null;
        /**
         * Cada punto de lo que hacías en este puesto.
         */
        responsibilities?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos del menú de navegación, botones y etiquetas generales. Cambia solo el 'valor', no la 'clave'.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-strings".
 */
export interface UiString {
  id: number;
  /**
   * Cada fila es un texto de la web. Deja la 'Clave' como está y edita solo el 'Valor'.
   */
  strings?:
    | {
        /**
         * Identificador técnico. Bloqueado a propósito para que no se pueda romper.
         */
        key: string;
        /**
         * El texto que se muestra en la web. Este sí puedes cambiarlo.
         */
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  brand?: T;
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        anchor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        title?: T;
        subtitle?: T;
        body?: T;
        cta1?: T;
        cta2?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-text_select".
 */
export interface SectionTextSelect<T extends boolean = true> {
  webApps?:
    | T
    | {
        home?:
          | T
          | {
              heading?: T;
              description?: T;
              studioName?: T;
              roleDescription?: T;
              cta?: T;
            };
        page?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  branding?:
    | T
    | {
        home?:
          | T
          | {
              heading?: T;
              description?: T;
              studioName?: T;
              roleDescription?: T;
              cta?: T;
              sectionHeading?: T;
            };
        page?:
          | T
          | {
              title?: T;
              description?: T;
              subtitleSports?: T;
              subtitleBeauty?: T;
            };
      };
  photography?:
    | T
    | {
        home?:
          | T
          | {
              heading?: T;
              description?: T;
              studioName?: T;
              roleDescription?: T;
              cta?: T;
            };
        page?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  marketing360?:
    | T
    | {
        home?:
          | T
          | {
              heading?: T;
              description?: T;
              studioName?: T;
              roleDescription?: T;
              cta?: T;
            };
        page?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  uxui?:
    | T
    | {
        home?:
          | T
          | {
              heading?: T;
              tagline?: T;
              description?: T;
              studioName?: T;
              roleDescription?: T;
              sketchImage?: T;
              sketchAlt?: T;
              cta?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-study_select".
 */
export interface CaseStudySelect<T extends boolean = true> {
  header?:
    | T
    | {
        title?: T;
        tagline?: T;
      };
  hero?:
    | T
    | {
        image?: T;
        alt?: T;
      };
  project?:
    | T
    | {
        name?: T;
        subtitle?: T;
        overview?:
          | T
          | {
              label?: T;
              text?: T;
              id?: T;
            };
      };
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  problemSolution?:
    | T
    | {
        problem?:
          | T
          | {
              label?: T;
              text?: T;
            };
        solution?:
          | T
          | {
              label?: T;
              text?: T;
            };
      };
  details?:
    | T
    | {
        headers?:
          | T
          | {
              tools?: T;
              team?: T;
              role?: T;
            };
        rows?:
          | T
          | {
              tools?: T;
              team?: T;
              role?: T;
              id?: T;
            };
      };
  timeline?:
    | T
    | {
        title?: T;
        durationLabel?: T;
        durationValue?: T;
        phases?:
          | T
          | {
              phase?: T;
              duration?: T;
              id?: T;
            };
      };
  journey?:
    | T
    | {
        title?: T;
        intro?:
          | T
          | {
              text?: T;
              id?: T;
            };
        labels?:
          | T
          | {
              action?: T;
              thought?: T;
              friction?: T;
            };
        stages?:
          | T
          | {
              number?: T;
              name?: T;
              action?: T;
              thought?: T;
              friction?: T;
              id?: T;
            };
        qa?:
          | T
          | {
              question?: T;
              answer?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  personas?:
    | T
    | {
        title?: T;
        intro?:
          | T
          | {
              text?: T;
              id?: T;
            };
        qa?:
          | T
          | {
              question?: T;
              answer?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        sectionLabels?:
          | T
          | {
              basicInfo?: T;
              channels?: T;
              motivations?: T;
              painPoints?: T;
            };
        cards?:
          | T
          | {
              name?: T;
              descriptor?: T;
              quote?: T;
              basicInfo?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              channels?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              motivations?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              painPoints?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  sketches?:
    | T
    | {
        title?: T;
        intro?:
          | T
          | {
              text?: T;
              id?: T;
            };
        qa?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  learnings?:
    | T
    | {
        title?: T;
        qa?:
          | T
          | {
              question?: T;
              answer?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  headings?:
    | T
    | {
        education?: T;
        tools?: T;
        languages?: T;
      };
  education?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tools?:
    | T
    | {
        value?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        body?: T;
        email?: T;
        phone?: T;
      };
  socialLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        copyrightPrefix?: T;
        rights?: T;
        privacy?: T;
        terms?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career_select".
 */
export interface CareerSelect<T extends boolean = true> {
  headings?:
    | T
    | {
        careerPath?: T;
        professionalExperience?: T;
      };
  experience?:
    | T
    | {
        role?: T;
        period?: T;
        responsibilities?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-strings_select".
 */
export interface UiStringsSelect<T extends boolean = true> {
  strings?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}